Update index.html
htmlacademy-htmlcss/354143-sedona-29 pull request #2
Opened 2020-09-15 20:52 UTC by nastinka

2020-09-16 17:13 UTC, zavsievich requested changes

2020-09-16 17:13 UTC, zavsievich commented on index.html
> +    <h2>Настоящий городок<h2>
Так как заголовок этой секции будет второго уровня (коммент к 31 строке), то эти заголовки лучше сделать на уровень ниже: `<h3></h3>`

2020-09-16 17:13 UTC, zavsievich commented on index.html
> +<input type="submit">
блок с формой лучше оставить пустым до тех пор, пока про него не расскажут на лекциях, но молодец, что проявила инициативу!

2020-09-16 17:13 UTC, zavsievich commented on index.html
> +  <h1>Контакты<h1>
На странице должен быть только один заголовок 1 уровня, поэтому лучше эти заголовки сделать вторым уровнем

2020-09-16 17:13 UTC, zavsievich commented on index.html
> +    тел: +7(495)666-01-66</p>
лучше сделать двумя различными элементами: вдруг дизайнер захочет поменять стили у ссылки или хэштега
переносы br можно использовать в заголовках там, где эти переносы нужны, стихотворениях и текстах, в которых эту предусмотрено типографикой. тут же это два отдельных элемента, почти никаких не связанных друг с другом

2020-09-16 17:13 UTC, zavsievich commented on index.html
> +    тел: +7(495)666-01-66</p>
для телефона можно использовать ссылку `<a href="tel:+7(495)666-01-66">+7(495)666-01-66</a>`, чтобы повысить UX

2020-09-16 17:13 UTC, zavsievich commented on index.html
> +    <a href="#">YouTube</a>
У этих ссылок есть иконки соц.сетей: пока что можно использовать заглушку 
https://via.placeholder.com/20x20

2020-09-16 17:13 UTC, zavsievich commented on index.html
> +    <a>
ссылка внутри ссылки?)

2020-09-16 17:13 UTC, zavsievich commented on index.html
> +<a href="https://htmlacademy.ru">HTML Academy</a>
также лучше делать отдельми элементами, а не разделять с помощью `</br>`

2020-09-16 17:13 UTC, zavsievich commented on index.html
> +        <li><a href="blank.html">Информация</li>
ссылки также не закрыты

2020-09-24 18:25 UTC, zavsievich requested changes

2020-09-24 18:25 UTC, zavsievich commented on index.html
>  </section>
@nastinka мне кажется, этому контенту лучше бы сиделось в main

2020-09-24 18:25 UTC, zavsievich commented on index.html
>    <section>
и помнишь, мы говорили, что секцию , которая начинается на 29 строчке, мы предварительно оборачиваем в секцию, которая начинается на 24?)

2020-09-24 18:25 UTC, zavsievich commented on index.html
>    <h1>Контакты<h1>
второй h1!

2020-09-24 18:25 UTC, zavsievich commented on index.html
>    <h1>Ссылки на соцсети<h1>
третий h1!

2020-09-24 18:25 UTC, zavsievich commented on index.html
>      <a>
ссылка должна вести на страницу интенсива: https://up.htmlacademy.ru/htmlcss/29

2020-09-24 18:37 UTC, nastinka commented on index.html
>    <section>
а как тогда правильно закрывать? получится подряд:
</section>
</section> ?

2020-09-24 19:33 UTC, zavsievich commented on index.html
> +    <h1>Городок Sedona</h1>
а почему h1 не в main?

2020-09-24 19:33 UTC, zavsievich commented on index.html
> +    <a>
не слишком ли много ссылок тут?) перепроверь, пожалуйста

2020-09-25 20:44 UTC, zavsievich commented on Readme.md
> +* Наставник: [Захар Авсиевичu](https://htmlacademy.ru/profile/id846143).
ой, Насть, тут с моей фамилией что-то...

2020-09-30 18:00 UTC, zavsievich approved these changes

2020-09-30 18:00 UTC, merged